In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path().resolve().parent / 'src'))

In [2]:
import pandas as pd
from main import run_pipeline

In [3]:
s = 'AAPL'
run_pipeline(s)

Processing AAPL...
Success! Files saved to: ../outputs/AAPL_report

In [4]:
keys = ['balance_sheet', 'cash_flow', 'income_statement', 'insights']
bs_, cf_, is_, in_ = tuple(keys)
dfs = {}
for k in keys:
    dfs[k] = pd.read_csv(f'../outputs/{s}_report/{k}.csv')

In [5]:
dfs[bs_].head()

,Date,Treasury Shares Number,Ordinary Shares Number,Share Issued,Net Debt,Total Debt,Tangible Book Value,Invested Capital,Working Capital,Net Tangible Assets,...,Other Current Assets,Inventory,Receivables,Other Receivables,Accounts Receivable,Cash Cash Equivalents And Short Term Investments,Other Short Term Investments,Cash And Cash Equivalents,Cash Equivalents,Cash Financial
0,2025-09-30,NaN,1.477326e+10,1.477326e+10,6.272300e+10,9.865700e+10,7.373300e+10,1.723900e+11,-1.767400e+10,7.373300e+10,...,1.458500e+10,5.718000e+09,7.295700e+10,3.318000e+10,3.977700e+10,5.469700e+10,1.876300e+10,3.593400e+10,7.667000e+09,2.826700e+10
1,2024-09-30,NaN,1.511679e+10,1.511679e+10,7.668600e+10,1.066290e+11,5.695000e+10,1.635790e+11,-2.340500e+10,5.695000e+10,...,1.428700e+10,7.286000e+09,6.624300e+10,3.283300e+10,3.341000e+10,6.517100e+10,3.522800e+10,2.994300e+10,2.744000e+09,2.719900e+10
2,2023-09-30,0.0,1.555006e+10,1.555006e+10,8.112300e+10,1.110880e+11,6.214600e+10,1.732340e+11,-1.742000e+09,6.214600e+10,...,1.469500e+10,6.331000e+09,6.098500e+10,3.147700e+10,2.950800e+10,6.155500e+10,3.159000e+10,2.996500e+10,1.606000e+09,2.835900e+10
3,2022-09-30,NaN,1.594342e+10,1.594342e+10,9.642300e+10,1.324800e+11,5.067200e+10,1.707410e+11,-1.857700e+10,5.067200e+10,...,2.122300e+10,4.946000e+09,6.093200e+10,3.274800e+10,2.818400e+10,4.830400e+10,2.465800e+10,2.364600e+10,5.100000e+09,1.854600e+10
4,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dfs[cf_].head()

,Date,Free Cash Flow,Repurchase Of Capital Stock,Repayment Of Debt,Issuance Of Debt,Issuance Of Capital Stock,Capital Expenditure,Interest Paid Supplemental Data,Income Tax Paid Supplemental Data,End Cash Position,...,Change In Inventory,Change In Receivables,Changes In Account Receivables,Other Non Cash Items,Stock Based Compensation,Deferred Tax,Deferred Income Tax,Depreciation Amortization Depletion,Depreciation And Amortization,Net Income From Continuing Operations
0,2025-09-30,9.876700e+10,-9.071100e+10,-1.093200e+10,4.481000e+09,NaN,-1.271500e+10,NaN,4.336900e+10,3.593400e+10,...,1.400000e+09,-7.029000e+09,-6.682000e+09,-8.900000e+07,1.286300e+10,NaN,NaN,1.169800e+10,1.169800e+10,1.120100e+11
1,2024-09-30,1.088070e+11,-9.494900e+10,-9.958000e+09,0.000000e+00,NaN,-9.447000e+09,NaN,2.610200e+10,2.994300e+10,...,-1.046000e+09,-5.144000e+09,-3.788000e+09,-2.266000e+09,1.168800e+10,NaN,NaN,1.144500e+10,1.144500e+10,9.373600e+10
2,2023-09-30,9.958400e+10,-7.755000e+10,-1.115100e+10,5.228000e+09,NaN,-1.095900e+10,3.803000e+09,1.867900e+10,3.073700e+10,...,-1.618000e+09,-4.170000e+08,-1.688000e+09,-2.227000e+09,1.083300e+10,NaN,NaN,1.151900e+10,1.151900e+10,9.699500e+10
3,2022-09-30,1.114430e+11,-8.940200e+10,-9.543000e+09,5.465000e+09,NaN,-1.070800e+10,2.865000e+09,1.957300e+10,2.497700e+10,...,1.484000e+09,-9.343000e+09,-1.823000e+09,1.006000e+09,9.038000e+09,8.950000e+08,8.950000e+08,1.110400e+10,1.110400e+10,9.980300e+10
4,2021-09-30,NaN,NaN,NaN,NaN,1.105000e+09,NaN,2.687000e+09,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,-4.774000e+09,-4.774000e+09,NaN,NaN,NaN

In [7]:
dfs[is_].head()

,Date,Tax Effect Of Unusual Items,Tax Rate For Calcs,Normalized EBITDA,Net Income From Continuing Operation Net Minority Interest,Reconciled Depreciation,Reconciled Cost Of Revenue,EBITDA,EBIT,Net Interest Income,...,Interest Expense Non Operating,Interest Income Non Operating,Operating Income,Operating Expense,Research And Development,Selling General And Administration,Gross Profit,Cost Of Revenue,Total Revenue,Operating Revenue
0,2025-09-30,0.0,0.156,1.447480e+11,1.120100e+11,1.169800e+10,2.209600e+11,1.447480e+11,1.330500e+11,NaN,...,NaN,NaN,1.330500e+11,6.215100e+10,3.455000e+10,2.760100e+10,1.952010e+11,2.209600e+11,4.161610e+11,4.161610e+11
1,2024-09-30,0.0,0.241,1.346610e+11,9.373600e+10,1.144500e+10,2.103520e+11,1.346610e+11,1.232160e+11,NaN,...,NaN,NaN,1.232160e+11,5.746700e+10,3.137000e+10,2.609700e+10,1.806830e+11,2.103520e+11,3.910350e+11,3.910350e+11
2,2023-09-30,0.0,0.147,1.258200e+11,9.699500e+10,1.151900e+10,2.141370e+11,1.258200e+11,1.143010e+11,-183000000.0,...,3.933000e+09,3.750000e+09,1.143010e+11,5.484700e+10,2.991500e+10,2.493200e+10,1.691480e+11,2.141370e+11,3.832850e+11,3.832850e+11
3,2022-09-30,0.0,0.162,1.305410e+11,9.980300e+10,1.110400e+10,2.235460e+11,1.305410e+11,1.194370e+11,-106000000.0,...,2.931000e+09,2.825000e+09,1.194370e+11,5.134500e+10,2.625100e+10,2.509400e+10,1.707820e+11,2.235460e+11,3.943280e+11,3.943280e+11
4,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,198000000.0,...,2.645000e+09,2.843000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
dfs[in_].head()

         Date    Net Income  Total Revenue  Profit Margin
0  2025-09-30  1.120100e+11   4.161610e+11       0.269151
1  2024-09-30  9.373600e+10   3.910350e+11       0.239713
2  2023-09-30  9.699500e+10   3.832850e+11       0.253062
3  2022-09-30  9.980300e+10   3.943280e+11       0.253096
4  2021-09-30           NaN            NaN            NaN