In [1]:
import sys
from pathlib import Path
sys.path.append(str(Path().resolve().parent / 'src'))

In [2]:
import pandas as pd
from main import run_pipeline

In [3]:
s = 'AAPL'
run_pipeline(s)

Processing AAPL...
Success! Files saved to: D:\Users\Work\Documents\Github Repo\2026\financial-statement-generator\outputs\AAPL_report

In [4]:
keys = ['balance_sheet', 'cash_flow', 'income_statement', 'insights']
keys = ['key_ratios','summary_statement_millions']
dfs = {}
for k in keys:
    dfs[k] = pd.read_csv(f'../outputs/{s}_report/{k}.csv')

In [8]:
dfs[keys[0]].head(10)

         Date  Net Profit Margin
0  2025-09-30             0.2692
1  2024-09-30             0.2397
2  2023-09-30             0.2531
3  2022-09-30             0.2531
4  2021-09-30                NaN

In [6]:
dfs[keys[1]].head()

,Date,Total Revenue,Gross Profit,Operating Income,Net Income,Total Assets,Free Cash Flow,Total Debt
0,2025-09-30,416161.0,195201.0,133050.0,112010.0,359241.0,98767.0,98657.0
1,2024-09-30,391035.0,180683.0,123216.0,93736.0,364980.0,108807.0,106629.0
2,2023-09-30,383285.0,169148.0,114301.0,96995.0,352583.0,99584.0,111088.0
3,2022-09-30,394328.0,170782.0,119437.0,99803.0,352755.0,111443.0,132480.0
4,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN